/** The curated half of the MCP market: servers we have looked at, from publishers we can name, with
 *  the exact launch line spelled out. Offline by design — `rovecode mcp search` answers from this list
 *  before it asks the registry, and /mcp with an empty query shows only this list. Rules for an entry:
 *  the publisher is the org that owns the package or the host; secrets travel by environment variable
 *  (or a header for a remote), never as an argument; anything OAuth-only is left out because our http
 *  transport carries a header, not a browser flow. Keep it short — this is a shelf, not a mirror. */

import type { MarketEntry } from "./market.ts";

const npx = (pkg: string, ...rest: string[]): string[] => ["-y", pkg, ...rest];

export const CURATED: readonly MarketEntry[] = [
  { key: "filesystem", title: "Filesystem", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "Read, write, search and move files under the directories you name.",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("@modelcontextprotocol/server-filesystem"), env: [], pending: ["<directory the server may touch>"] }] },
  { key: "memory", title: "Memory", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "A knowledge graph the model can remember across sessions with (entities, relations, observations).",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("@modelcontextprotocol/server-memory"), env: [], pending: [] }] },
  { key: "sequential-thinking", title: "Sequential Thinking", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "A scratchpad tool for step-by-step reasoning with revisions and branches.",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("@modelcontextprotocol/server-sequential-thinking"), env: [], pending: [] }] },
  { key: "everything", title: "Everything (test server)", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "Exercises every MCP feature — prompts, resources, sampling, progress. For testing a client, not for work.",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("@modelcontextprotocol/server-everything"), env: [], pending: [] }] },
  { key: "fetch", title: "Fetch", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "Fetch a URL and hand the page back as markdown (Python; needs uv).",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "uvx", command: "uvx", args: ["mcp-server-fetch"], env: [], pending: [] }] },
  { key: "git", title: "Git", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "Read and search git repositories: log, diff, show, status (Python; needs uv).",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "uvx", command: "uvx", args: ["mcp-server-git"], env: [], pending: [] }] },
  { key: "time", title: "Time", source: "curated", publisher: "modelcontextprotocol (Anthropic)",
    description: "Current time and timezone conversion (Python; needs uv).",
    repository: "https://github.com/modelcontextprotocol/servers",
    installs: [{ kind: "stdio", runtime: "uvx", command: "uvx", args: ["mcp-server-time"], env: [], pending: [] }] },
  { key: "github", title: "GitHub", source: "curated", publisher: "GitHub",
    description: "Issues, pull requests, code search and Actions on GitHub — remote with a personal access token, or the official image via docker.",
    repository: "https://github.com/github/github-mcp-server",
    installs: [
      { kind: "http", url: "https://api.githubcopilot.com/mcp/", headers: [{ name: "Authorization", template: "Bearer {GITHUB_PAT}", required: true, secret: true, description: "a GitHub personal access token" }] },
      { kind: "stdio", runtime: "docker", command: "docker", args: ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"],
        env: [{ name: "GITHUB_PERSONAL_ACCESS_TOKEN", required: true, secret: true, description: "a GitHub personal access token" }], pending: [] },
    ] },
  { key: "playwright", title: "Playwright", source: "curated", publisher: "Microsoft",
    description: "Drive a real browser through accessibility snapshots: navigate, click, type, screenshot.",
    repository: "https://github.com/microsoft/playwright-mcp",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("@playwright/mcp@latest"), env: [], pending: [] }] },
  { key: "context7", title: "Context7", source: "curated", publisher: "Upstash",
    description: "Up-to-date library documentation and code examples for the versions you actually use.",
    repository: "https://github.com/upstash/context7",
    installs: [
      { kind: "http", url: "https://mcp.context7.com/mcp", headers: [{ name: "CONTEXT7_API_KEY", required: false, secret: true, description: "optional API key for higher limits" }] },
      { kind: "stdio", runtime: "npx", command: "npx", args: npx("@upstash/context7-mcp"), env: [{ name: "CONTEXT7_API_KEY", required: false, secret: true, description: "optional API key for higher limits" }], pending: [] },
    ] },
  { key: "brave-search", title: "Brave Search", source: "curated", publisher: "Brave",
    description: "Web, news, image and local search through the Brave Search API.",
    repository: "https://github.com/brave/brave-search-mcp-server",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("@brave/brave-search-mcp-server"), env: [{ name: "BRAVE_API_KEY", required: true, secret: true, description: "Brave Search API key" }], pending: [] }] },
  { key: "firecrawl", title: "Firecrawl", source: "curated", publisher: "Firecrawl (Mendable)",
    description: "Scrape, crawl and extract structured data from websites.",
    repository: "https://github.com/mendableai/firecrawl-mcp-server",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("firecrawl-mcp"), env: [{ name: "FIRECRAWL_API_KEY", required: true, secret: true, description: "Firecrawl API key" }], pending: [] }] },
  { key: "tavily", title: "Tavily", source: "curated", publisher: "Tavily",
    description: "Search and extract built for agents: web search, page extraction, site crawl.",
    repository: "https://github.com/tavily-ai/tavily-mcp",
    installs: [{ kind: "stdio", runtime: "npx", command: "npx", args: npx("tavily-mcp"), env: [{ name: "TAVILY_API_KEY", required: true, secret: true, description: "Tavily API key" }], pending: [] }] },
  { key: "exa", title: "Exa", source: "curated", publisher: "Exa",
    description: "Neural web search and page contents for AI; the remote works without a key at a low rate.",
    repository: "https://github.com/exa-labs/exa-mcp-server",
    installs: [{ kind: "http", url: "https://mcp.exa.ai/mcp", headers: [] }] },
  { key: "deepwiki", title: "DeepWiki", source: "curated", publisher: "Cognition (Devin)",
    description: "Ask questions about any public GitHub repository, answered from its generated wiki. No key.",
    homepage: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    installs: [{ kind: "http", url: "https://mcp.deepwiki.com/mcp", headers: [] }] },
  { key: "cloudflare-docs", title: "Cloudflare Docs", source: "curated", publisher: "Cloudflare",
    description: "Search Cloudflare's developer documentation. No key.",
    repository: "https://github.com/cloudflare/mcp-server-cloudflare",
    installs: [{ kind: "http", url: "https://docs.mcp.cloudflare.com/mcp", headers: [] }] },
];
