#!/usr/bin/env bash
# Regenerate the three files the website renders and publish them into the site repository.
#
#   scripts/publish-site-data.sh                 regenerate, commit and push to 9Code-Labs/rovecode-site
#   scripts/publish-site-data.sh --dry-run       regenerate, show the diff, put the checkout back
#   scripts/publish-site-data.sh --dry-run --keep   ...and leave the regenerated files in place
#   SITE_REPO=/path/to/rovecode-site scripts/publish-site-data.sh
#
# The site moved to its own repository on 2026-09-06 (Berkay's call). What did not move is the CONTENT:
# the documentation is docs/*.md here, the market is src/market/catalogs/*.json, src/mcp/market-catalog.ts
# and plugins/ here, and the landing page's numbers are counted from this tree. So the generators stayed,
# and what crosses the boundary is their output — three JSON files that the site repository holds as
# input and builds without ever reaching outside itself.
#
# The direction matters and is one-way: this script writes into the site repo, never the other way. If
# someone edits src/generated/*.json over there, the next publish overwrites it, which is why the site's
# README says content changes belong here.
set -euo pipefail

DRY=0
for a in "$@"; do case "$a" in --dry-run) DRY=1 ;; esac; done

HERE="$(cd "$(dirname "$0")/.." && pwd)"
SITE_REPO="${SITE_REPO:-$(cd "$HERE/.." && pwd)/rovecode-site}"
GEN="$SITE_REPO/src/generated"

[ -d "$SITE_REPO/.git" ] || { echo "no site repo at $SITE_REPO — clone 9Code-Labs/rovecode-site beside this one, or set SITE_REPO"; exit 2; }

# The generators take SITE_DIR and ROVECODE_REPO, so they run in place and write straight into the site
# checkout: no staging tree, no copies, and no second layout for anyone to keep in sync. Their only
# third-party dependency is `marked`, resolved from the site repo's node_modules.
export SITE_DIR="$SITE_REPO"
export ROVECODE_REPO="$HERE"
export NODE_PATH="$SITE_REPO/node_modules"

echo "== generate"
BEFORE="$(mktemp -d)"; trap 'rm -rf "$BEFORE"' EXIT
for f in facts.json docs.json market.json; do cp "$GEN/$f" "$BEFORE/$f" 2>/dev/null || : ; done
( cd "$SITE_REPO" && VITE_DOCS=1 VITE_MARKET=1 node "$HERE/scripts/site-generators/facts.mjs"   && VITE_DOCS=1 node "$HERE/scripts/site-generators/docs-build.mjs"   && VITE_MARKET=1 bun "$HERE/scripts/site-generators/market.mjs" )

for f in facts.json docs.json market.json; do
  [ -s "$GEN/$f" ] || { echo "generator produced no $f — refusing to publish"; exit 1; }
done

echo "== compare"
changed=0
for f in facts.json docs.json market.json; do
  if ! cmp -s "$BEFORE/$f" "$GEN/$f"; then
    changed=1
    echo "  $f differs ($(wc -c < "$BEFORE/$f" 2>/dev/null || echo 0) → $(wc -c < "$GEN/$f") bytes)"
  fi
done
[ "$changed" = 1 ] || { echo "nothing to publish — the site already renders this tree"; exit 0; }

# --dry-run puts the checkout back exactly as it found it. The first version left the regenerated files
# in place "so the operator can look at them", and that made the NEXT real run see no difference and
# publish nothing — a dry run that changes what a real run does is not a dry run. The summary above is
# what it was asked for; `--keep` is there for when the files themselves are wanted.
if [ "$DRY" = 1 ]; then
  case " $* " in *" --keep "*) echo "-- --dry-run --keep: regenerated in $GEN, not committed" ;;
    *) for f in facts.json docs.json market.json; do [ -f "$BEFORE/$f" ] && cp "$BEFORE/$f" "$GEN/$f"; done
       echo "-- --dry-run: nothing written; the checkout is as it was" ;;
  esac
  exit 0
fi

( cd "$SITE_REPO"
  git add src/generated
  git commit -q -m "data: republish from rovecode@$(cd "$HERE" && git rev-parse --short HEAD)

Regenerated by scripts/publish-site-data.sh in the rovecode repository. Content changes belong there —
docs/*.md, src/market/catalogs/*.json, src/mcp/market-catalog.ts, plugins/ — and arrive here as data."
  git push -q origin HEAD
  echo "published → $(git log --oneline -1)" )
